---

########################################################################
# Generate testing Jenkins jobs.
########################################################################

- name: Create a list of Blue-Green testing jobs for AWS
  shell: echo {{ item.path }}
  with_filetree: ../../../provisioners/jenkins/jenkinsfiles/aem-opencloud/testing/aws/
  when: item.state == 'file' and item.path is match('.*blue-green')
  register: testing_blue_green_jobs

- name: Trim skipped Blue-Green testing jobs for AWS
  set_fact:
    testing_blue_green_jobs_trimmed: "{{ testing_blue_green_jobs | trim_skipped() }}"

- name: Create a list of recovery testing jobs for AWS
  shell: echo {{ item.path }}
  with_filetree: ../../../provisioners/jenkins/jenkinsfiles/aem-opencloud/testing/aws/
  when: item.state == 'file' and item.path is match('.*recovery')
  register: testing_recovery_jobs

- name: Trim skipped recovery testing jobs for AWS
  set_fact:
    testing_recovery_jobs_trimmed: "{{ testing_recovery_jobs | trim_skipped() }}"

- name: Create a list of platform full-set testing jobs for AWS
  shell: echo {{ item.path }}
  with_filetree: ../../../provisioners/jenkins/jenkinsfiles/aem-opencloud/testing/aws/
  when: item.state == 'file' and item.path is match('.*full-set-platform')
  register: testing_platform_full_set_jobs

- name: Trim skipped platform full-set testing jobs for AWS
  set_fact:
    testing_platform_full_set_jobs_trimmed: "{{ testing_platform_full_set_jobs | trim_skipped() }}"

- name: Create a list of platform consolidated testing jobs for AWS
  shell: echo {{ item.path }}
  with_filetree: ../../../provisioners/jenkins/jenkinsfiles/aem-opencloud/testing/aws/
  when: item.state == 'file' and item.path is match('.*consolidated-platform')
  register: testing_platform_consolidated_jobs

- name: Trim skipped platform consolidated testing jobs for AWS
  set_fact:
    testing_platform_consolidated_jobs_trimmed: "{{ testing_platform_consolidated_jobs | trim_skipped() }}"

- name: Create a list of security full-set testing jobs for AWS
  shell: echo {{ item.path }}
  with_filetree: ../../../provisioners/jenkins/jenkinsfiles/aem-opencloud/testing/aws/
  when: item.state == 'file' and item.path is match('.*full-set-security')
  register: testing_security_full_set_jobs

- name: Trim skipped security full-set testing jobs for AWS
  set_fact:
    testing_security_full_set_jobs_trimmed: "{{ testing_security_full_set_jobs | trim_skipped() }}"

- name: Create a list of security consolidated testing jobs for AWS
  shell: echo {{ item.path }}
  with_filetree: ../../../provisioners/jenkins/jenkinsfiles/aem-opencloud/testing/aws/
  when: item.state == 'file' and item.path is match('.*consolidated-security')
  register: testing_security_consolidated_jobs

- name: Trim skipped security consolidated testing jobs for AWS
  set_fact:
    testing_security_consolidated_jobs_trimmed: "{{ testing_security_consolidated_jobs | trim_skipped() }}"

- name: Create a list of promote author standby full-set testing jobs for AWS
  shell: echo {{ item.path }}
  with_filetree: ../../../provisioners/jenkins/jenkinsfiles/aem-opencloud/testing/aws/
  when: item.state == 'file' and item.path is match('.*promote-author-standby-full-set')
  register: testing_promote_author_standby_jobs

- name: Trim skipped promote author standby full-set testing jobs for AWS
  set_fact:
    testing_promote_author_standby_jobs_trimmed: "{{ testing_promote_author_standby_jobs | trim_skipped() }}"

- name: "Generate jobs for Blue-Green testing configuration profile directories"
  file:
    path: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/testing/aws/{{ item[0].item.path }}-{{ item[2].item.path }}-{{ item[3].item.path }}-{{ item[4].item.path }}/{{ item[1].item.path }}/
    state: directory
    mode: '0776'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_full_set_profiles_trimmed.results }}"
    - "{{ testing_blue_green_jobs_trimmed.results }}"
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
    - "{{ aem_test_suite_profiles_trimmed.results }}"
    - "{{ aem_aws_stack_builder_aem_stack_manager_profiles_trimmed.results }}"

- name: "Generate jobs for recovery testing configuration profile directories"
  file:
    path: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/testing/aws/{{ item[0].item.path }}-{{ item[2].item.path }}-{{ item[3].item.path }}-{{ item[4].item.path }}/{{ item[1].item.path }}/
    state: directory
    mode: '0776'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_full_set_profiles_trimmed.results }}"
    - "{{ testing_recovery_jobs_trimmed.results }}"
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
    - "{{ aem_test_suite_profiles_trimmed.results }}"
    - "{{ aem_aws_stack_builder_aem_stack_manager_profiles_trimmed.results }}"

- name: "Generate jobs for platform full-set testing configuration profile directories"
  file:
    path: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/testing/aws/{{ item[0].item.path }}-{{ item[2].item.path }}-{{ item[3].item.path }}-{{ item[4].item.path }}/{{ item[1].item.path }}/
    state: directory
    mode: '0776'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_full_set_profiles_trimmed.results }}"
    - "{{ testing_platform_full_set_jobs_trimmed.results }}"
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
    - "{{ aem_test_suite_profiles_trimmed.results }}"
    - "{{ aem_aws_stack_builder_aem_stack_manager_profiles_trimmed.results }}"

- name: "Generate jobs for platform consolidated testing configuration profile directories"
  file:
    path: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/testing/aws/{{ item[0].item.path }}-{{ item[2].item.path }}-{{ item[3].item.path }}-{{ item[4].item.path }}/{{ item[1].item.path }}/
    state: directory
    mode: '0776'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_consolidated_profiles_trimmed.results }}"
    - "{{ testing_platform_consolidated_jobs_trimmed.results }}"
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
    - "{{ aem_test_suite_profiles_trimmed.results }}"
    - "{{ aem_aws_stack_builder_aem_stack_manager_profiles_trimmed.results }}"

- name: "Generate jobs for security full-set testing configuration profile directories"
  file:
    path: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/testing/aws/{{ item[0].item.path }}-{{ item[2].item.path }}-{{ item[3].item.path }}-{{ item[4].item.path }}/{{ item[1].item.path }}/
    state: directory
    mode: '0776'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_full_set_profiles_trimmed.results }}"
    - "{{ testing_security_full_set_jobs_trimmed.results }}"
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
    - "{{ aem_test_suite_profiles_trimmed.results }}"
    - "{{ aem_aws_stack_builder_aem_stack_manager_profiles_trimmed.results }}"

- name: "Generate jobs for security consolidated testing configuration profile directories"
  file:
    path: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/testing/aws/{{ item[0].item.path }}-{{ item[2].item.path }}-{{ item[3].item.path }}-{{ item[4].item.path }}/{{ item[1].item.path }}/
    state: directory
    mode: '0776'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_consolidated_profiles_trimmed.results }}"
    - "{{ testing_security_consolidated_jobs_trimmed.results }}"
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
    - "{{ aem_test_suite_profiles_trimmed.results }}"
    - "{{ aem_aws_stack_builder_aem_stack_manager_profiles_trimmed.results }}"

- name: "Generate jobs for promote author standby full-set testing configuration profile directories"
  file:
    path: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/testing/aws/{{ item[0].item.path }}-{{ item[2].item.path }}-{{ item[3].item.path }}-{{ item[4].item.path }}/{{ item[1].item.path }}/
    state: directory
    mode: '0776'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_full_set_profiles_trimmed.results }}"
    - "{{ testing_promote_author_standby_jobs_trimmed.results }}"
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
    - "{{ aem_test_suite_profiles_trimmed.results }}"
    - "{{ aem_aws_stack_builder_aem_stack_manager_profiles_trimmed.results }}"

- name: "Generate jobs for Blue-Green testing configuration config.xml"
  template:
    src: '../../../templates/ansible/jenkins/config/category-config-profile.xml.j2'
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/testing/aws/{{ item[0].item.path }}-{{ item[2].item.path }}-{{ item[3].item.path }}-{{ item[4].item.path }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_full_set_profiles_trimmed.results }}"
    - "{{ testing_blue_green_jobs_trimmed.results }}"
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
    - "{{ aem_test_suite_profiles_trimmed.results }}"
    - "{{ aem_aws_stack_builder_aem_stack_manager_profiles_trimmed.results }}"

- name: "Generate jobs for recovery testing configuration config.xml"
  template:
    src: '../../../templates/ansible/jenkins/config/category-config-profile.xml.j2'
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/testing/aws/{{ item[0].item.path }}-{{ item[2].item.path }}-{{ item[3].item.path }}-{{ item[4].item.path }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_full_set_profiles_trimmed.results }}"
    - "{{ testing_recovery_jobs_trimmed.results }}"
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
    - "{{ aem_test_suite_profiles_trimmed.results }}"
    - "{{ aem_aws_stack_builder_aem_stack_manager_profiles_trimmed.results }}"

- name: "Generate jobs for platform full-set testing configuration config.xml"
  template:
    src: '../../../templates/ansible/jenkins/config/category-config-profile.xml.j2'
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/testing/aws/{{ item[0].item.path }}-{{ item[2].item.path }}-{{ item[3].item.path }}-{{ item[4].item.path }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_full_set_profiles_trimmed.results }}"
    - "{{ testing_platform_full_set_jobs_trimmed.results }}"
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
    - "{{ aem_test_suite_profiles_trimmed.results }}"
    - "{{ aem_aws_stack_builder_aem_stack_manager_profiles_trimmed.results }}"

- name: "Generate jobs for platform consolidated testing configuration config.xml"
  template:
    src: '../../../templates/ansible/jenkins/config/category-config-profile.xml.j2'
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/testing/aws/{{ item[0].item.path }}-{{ item[2].item.path }}-{{ item[3].item.path }}-{{ item[4].item.path }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_consolidated_profiles_trimmed.results }}"
    - "{{ testing_platform_consolidated_jobs_trimmed.results }}"
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
    - "{{ aem_test_suite_profiles_trimmed.results }}"
    - "{{ aem_aws_stack_builder_aem_stack_manager_profiles_trimmed.results }}"

- name: "Generate jobs for security full-set testing configuration config.xml"
  template:
    src: '../../../templates/ansible/jenkins/config/category-config-profile.xml.j2'
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/testing/aws/{{ item[0].item.path }}-{{ item[2].item.path }}-{{ item[3].item.path }}-{{ item[4].item.path }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_full_set_profiles_trimmed.results }}"
    - "{{ testing_security_full_set_jobs_trimmed.results }}"
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
    - "{{ aem_test_suite_profiles_trimmed.results }}"
    - "{{ aem_aws_stack_builder_aem_stack_manager_profiles_trimmed.results }}"

- name: "Generate jobs for security consolidated testing configuration config.xml"
  template:
    src: '../../../templates/ansible/jenkins/config/category-config-profile.xml.j2'
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/testing/aws/{{ item[0].item.path }}-{{ item[2].item.path }}-{{ item[3].item.path }}-{{ item[4].item.path }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_consolidated_profiles_trimmed.results }}"
    - "{{ testing_security_consolidated_jobs_trimmed.results }}"
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
    - "{{ aem_test_suite_profiles_trimmed.results }}"
    - "{{ aem_aws_stack_builder_aem_stack_manager_profiles_trimmed.results }}"

- name: "Generate jobs for promote author standby full-set testing configuration config.xml"
  template:
    src: '../../../templates/ansible/jenkins/config/category-config-profile.xml.j2'
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/testing/aws/{{ item[0].item.path }}-{{ item[2].item.path }}-{{ item[3].item.path }}-{{ item[4].item.path }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_full_set_profiles_trimmed.results }}"
    - "{{ testing_promote_author_standby_jobs_trimmed.results }}"
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
    - "{{ aem_test_suite_profiles_trimmed.results }}"
    - "{{ aem_aws_stack_builder_aem_stack_manager_profiles_trimmed.results }}"

- name: "Generate jobs for Blue-Green testing config.xml"
  vars:
    aem_architecture_type: "{{ 'consolidated' if item[1].stdout is match('.*consolidated*') else 'full-set' }}"
  template:
    src: ../../../templates/ansible/jenkins/config/jobs-testing-blue-green.xml.j2
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/testing/aws/{{ item[0].item.path }}-{{ item[2].item.path }}-{{ item[3].item.path }}-{{ item[4].item.path }}/{{ item[1].item.path }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_full_set_profiles_trimmed.results }}"
    - "{{ testing_blue_green_jobs_trimmed.results }}"
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
    - "{{ aem_test_suite_profiles_trimmed.results }}"
    - "{{ aem_aws_stack_builder_aem_stack_manager_profiles_trimmed.results }}"

- name: "Generate jobs for recovery testing config.xml"
  vars:
    aem_architecture_type: "{{ 'consolidated' if item[1].stdout is match('.*consolidated*') else 'full-set' }}"
  template:
    src: ../../../templates/ansible/jenkins/config/jobs-testing.xml.j2
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/testing/aws/{{ item[0].item.path }}-{{ item[2].item.path }}-{{ item[3].item.path }}-{{ item[4].item.path }}/{{ item[1].item.path }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_full_set_profiles_trimmed.results }}"
    - "{{ testing_recovery_jobs_trimmed.results }}"
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
    - "{{ aem_test_suite_profiles_trimmed.results }}"
    - "{{ aem_aws_stack_builder_aem_stack_manager_profiles_trimmed.results }}"

- name: "Generate jobs for platform full-set testing config.xml"
  vars:
    aem_architecture_type: "{{ 'consolidated' if item[1].stdout is match('.*consolidated*') else 'full-set' }}"
  template:
    src: ../../../templates/ansible/jenkins/config/jobs-testing-platform.xml.j2
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/testing/aws/{{ item[0].item.path }}-{{ item[2].item.path }}-{{ item[3].item.path }}-{{ item[4].item.path }}/{{ item[1].item.path }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_full_set_profiles_trimmed.results }}"
    - "{{ testing_platform_full_set_jobs_trimmed.results }}"
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
    - "{{ aem_test_suite_profiles_trimmed.results }}"
    - "{{ aem_aws_stack_builder_aem_stack_manager_profiles_trimmed.results }}"

- name: "Generate jobs for platform consolidated testing config.xml"
  vars:
    aem_architecture_type: "{{ 'consolidated' if item[1].stdout is match('.*consolidated*') else 'full-set' }}"
  template:
    src: ../../../templates/ansible/jenkins/config/jobs-testing-platform.xml.j2
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/testing/aws/{{ item[0].item.path }}-{{ item[2].item.path }}-{{ item[3].item.path }}-{{ item[4].item.path }}/{{ item[1].item.path }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_consolidated_profiles_trimmed.results }}"
    - "{{ testing_platform_consolidated_jobs_trimmed.results }}"
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
    - "{{ aem_test_suite_profiles_trimmed.results }}"
    - "{{ aem_aws_stack_builder_aem_stack_manager_profiles_trimmed.results }}"

- name: "Generate jobs for security full-set testing config.xml"
  vars:
    aem_architecture_type: "{{ 'consolidated' if item[1].stdout is match('.*consolidated*') else 'full-set' }}"
  template:
    src: ../../../templates/ansible/jenkins/config/jobs-testing-security.xml.j2
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/testing/aws/{{ item[0].item.path }}-{{ item[2].item.path }}-{{ item[3].item.path }}-{{ item[4].item.path }}/{{ item[1].item.path }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_full_set_profiles_trimmed.results }}"
    - "{{ testing_security_full_set_jobs_trimmed.results }}"
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
    - "{{ aem_test_suite_profiles_trimmed.results }}"
    - "{{ aem_aws_stack_builder_aem_stack_manager_profiles_trimmed.results }}"

- name: "Generate jobs for security consolidated testing config.xml"
  vars:
    aem_architecture_type: "{{ 'consolidated' if item[1].stdout is match('.*consolidated*') else 'full-set' }}"
  template:
    src: ../../../templates/ansible/jenkins/config/jobs-testing-consolidated-security.xml.j2
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/testing/aws/{{ item[0].item.path }}-{{ item[2].item.path }}-{{ item[3].item.path }}-{{ item[4].item.path }}/{{ item[1].item.path }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_consolidated_profiles_trimmed.results }}"
    - "{{ testing_security_consolidated_jobs_trimmed.results }}"
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
    - "{{ aem_test_suite_profiles_trimmed.results }}"
    - "{{ aem_aws_stack_builder_aem_stack_manager_profiles_trimmed.results }}"

- name: "Generate jobs for promote author standby full-set testing config.xml"
  vars:
    aem_architecture_type: "{{ 'consolidated' if item[1].stdout is match('.*consolidated*') else 'full-set' }}"
  template:
    src: ../../../templates/ansible/jenkins/config/jobs-testing.xml.j2
    dest: ../../../stage/jenkins/jobs/aem-opencloud-{{ aem_opencloud.version }}/testing/aws/{{ item[0].item.path }}-{{ item[2].item.path }}-{{ item[3].item.path }}-{{ item[4].item.path }}/{{ item[1].item.path }}/config.xml
    mode: '0644'
  with_nested:
    - "{{ aem_aws_stack_builder_aem_full_set_profiles_trimmed.results }}"
    - "{{ testing_promote_author_standby_jobs_trimmed.results }}"
    - "{{ aem_stack_manager_messenger_profiles_trimmed.results }}"
    - "{{ aem_test_suite_profiles_trimmed.results }}"
    - "{{ aem_aws_stack_builder_aem_stack_manager_profiles_trimmed.results }}"
