---
- name: AEM OpenCloud Manager Jenkins installer
  hosts: all
  gather_facts: no
  connection: local

  tasks:
    - name: "Provision Jenkins jobs"
      jenkins_job:
        config: "{{ lookup('file', '../../../stage/jenkins/jobs/{{ item.path }}') }}"
        name: "{{ item.path| replace('/config.xml', '') }}"
        password: "{{ lookup('env', 'JENKINS_PASSWORD') | default(jenkins.password, true) }}"
        url: "{{ jenkins.protocol }}://{{ jenkins.host }}:{{ jenkins.port }}"
        user: "{{ lookup('env', 'JENKINS_USERNAME') | default(jenkins.username, true) }}"
      with_filetree: ../../../stage/jenkins/jobs
      when: item.state == 'file'
