---
- name: Provision Jenkins with plugins
  hosts: all
  gather_facts: no
  connection: local

  vars:
    jenkins_plugins:
      - name: pipeline-utility-steps
        version: 2.3.0

  tasks:

    - name: Install Jenkins plugins
      jenkins_plugin:
        name: "{{ item.name }}"
        version: "{{ item.version }}"
        url_username: "{{ lookup('env', 'JENKINS_USERNAME') | default(jenkins.username, true) }}"
        url_password: "{{ lookup('env', 'JENKINS_PASSWORD') | default(jenkins.password, true) }}"
        url: "{{ jenkins.protocol }}://{{ jenkins.host }}:{{ jenkins.port }}"
        jenkins_home: "{{ jenkins.os.jenkins_home }}"
        owner: "{{ jenkins.os.user }}"
        group: "{{ jenkins.os.group }}"
      with_items: "{{ jenkins_plugins }}"
